#!/usr/bin/env python3
"""
Data-Driven Residuals Preprocessor (Memory Optimized)

This module provides functions to extract residuals from trained data-driven models
for use as features in other experiments. It loads data from .pth files
generated by LoadDatav3.py and returns residuals in memory.

This version repeats data residuals as physics residuals to maintain compatibility
with downstream analysis tools that expect 8 residual features.

Memory optimizations:
- Batch processing to avoid loading entire datasets
- Memory cleanup with explicit garbage collection
- Optional memory mapping for large files
- Streaming processing for large datasets
"""

import torch
import numpy as np
import os
import sys
import json
import gc
from typing import Dict, Tuple, Optional, Iterator
import logging

# Try to import tqdm for progress bars (optional)
try:
    from tqdm import tqdm
    HAS_TQDM = True
except ImportError:
    HAS_TQDM = False

# Try to import psutil for memory monitoring (optional)
try:
    import psutil
    HAS_PSUTIL = True
except ImportError:
    HAS_PSUTIL = False
    logger = logging.getLogger(__name__)
    logger.warning("psutil not available - memory monitoring disabled")

# Add project root to path
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from models.basicPINNv8 import ConfigurableMLP
from training_scripts.common_utils import load_best_model

# Setup logging (increased verbosity for debugging)
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


def get_memory_usage() -> float:
    """Get current memory usage in MB."""
    if not HAS_PSUTIL:
        return 0.0
    process = psutil.Process(os.getpid())
    return process.memory_info().rss / 1024 / 1024


def log_memory_usage(message: str = ""):
    """Log current memory usage."""
    if not HAS_PSUTIL:
        return
    memory_mb = get_memory_usage()
    logger.debug(f"{message}: {memory_mb:.1f} MB")


def cleanup_memory():
    """Force garbage collection and clear CUDA cache."""
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()


def load_pinn_data(pth_file: str, memory_map: bool = False) -> Tuple[torch.Tensor, torch.Tensor]:
    """
    Load X and y tensors from .pth files generated by LoadDatav3.py

    Args:
        pth_file: Path to the X .pth file (will automatically load corresponding Y file)
        memory_map: If True, use memory mapping for large files (experimental)

    Returns:
        Tuple of (X, y) tensors where:
        - X: Input features [n_rotation_speeds, n_timestamps_per_speed, 10]
        - y: Target accelerations [n_rotation_speeds, n_timestamps_per_speed, 4]

    Raises:
        FileNotFoundError: If X or Y file doesn't exist
        ValueError: If data format is unexpected
    """
    log_memory_usage("Before loading data")

    # Check if X file exists
    if not os.path.exists(pth_file):
        raise FileNotFoundError(f"X data file not found: {pth_file}")

    try:
        # Load X data with optional memory mapping
        if memory_map:
            # Use mmap for large files (experimental)
            X = torch.load(pth_file, map_location='cpu', mmap=True)
        else:
            X = torch.load(pth_file, map_location='cpu')
        log_memory_usage("After loading X data")
    except Exception as e:
        raise ValueError(f"Failed to load X data from {pth_file}: {e}")

    # Construct Y file path by replacing X with Y
    y_pth_file = pth_file.replace('/X_', '/Y_').replace('\\X_', '\\Y_')
    if pth_file.startswith('X_'):
        y_pth_file = pth_file.replace('X_', 'Y_', 1)
    elif 'X_' in pth_file:
        y_pth_file = pth_file.replace('X_', 'Y_')

    # Check if Y file exists
    if not os.path.exists(y_pth_file):
        raise FileNotFoundError(f"Y data file not found: {y_pth_file}")

    try:
        # Load Y data
        if memory_map:
            y = torch.load(y_pth_file, map_location='cpu', mmap=True)
        else:
            y = torch.load(y_pth_file, map_location='cpu')
        log_memory_usage("After loading Y data")
    except Exception as e:
        raise ValueError(f"Failed to load Y data from {y_pth_file}: {e}")

    # Basic validation of data shapes
    if X.ndim != 3 or y.ndim != 3:
        raise ValueError(f"Expected 3D tensors, got X: {X.shape}, y: {y.shape}")

    if X.shape[0] != y.shape[0] or X.shape[1] != y.shape[1]:
        raise ValueError(f"Shape mismatch between X {X.shape} and y {y.shape}")

    return X, y


def load_pinn_data_chunked(pth_file: str, chunk_size_mb: int = 100) -> Iterator[Tuple[torch.Tensor, torch.Tensor]]:
    """
    Load X and y tensors in chunks to save memory.

    Args:
        pth_file: Path to the X .pth file
        chunk_size_mb: Target chunk size in MB

    Yields:
        Tuples of (X_chunk, y_chunk) tensors
    """
    # First load the full data to understand structure
    X_full, y_full = load_pinn_data(pth_file)

    # Calculate chunk size based on memory target
    total_samples = X_full.shape[0] * X_full.shape[1]
    bytes_per_sample = X_full.element_size() * (X_full.shape[2] + y_full.shape[2])
    target_samples_per_chunk = (chunk_size_mb * 1024 * 1024) // bytes_per_sample

    # Calculate number of chunks for progress bar
    total_chunks = (total_samples + target_samples_per_chunk - 1) // target_samples_per_chunk

    logger.debug(f"Data: {total_samples} samples, ~{bytes_per_sample} bytes per sample")
    logger.debug(f"Target chunk size: {target_samples_per_chunk} samples ({total_chunks} chunks)")

    # Process in chunks with progress bar if tqdm available
    if HAS_TQDM:
        with tqdm(total=total_chunks, desc="Loading data chunks", unit="chunk") as pbar:
            for start_idx in range(0, total_samples, target_samples_per_chunk):
                end_idx = min(start_idx + target_samples_per_chunk, total_samples)

                # Extract chunk from flattened data
                X_chunk = X_full.reshape(-1, X_full.shape[2])[start_idx:end_idx]
                y_chunk = y_full.reshape(-1, y_full.shape[2])[start_idx:end_idx]

                log_memory_usage(f"Yielding chunk {start_idx}-{end_idx}")
                pbar.set_postfix({
                    'samples': f"{start_idx}-{end_idx}",
                    'size': f"{X_chunk.shape[0]} samples"
                })

                yield X_chunk, y_chunk

                # Clean up
                del X_chunk, y_chunk
                cleanup_memory()
                pbar.update(1)
    else:
        # Fallback without progress bar
        for start_idx in range(0, total_samples, target_samples_per_chunk):
            end_idx = min(start_idx + target_samples_per_chunk, total_samples)

            # Extract chunk from flattened data
            X_chunk = X_full.reshape(-1, X_full.shape[2])[start_idx:end_idx]
            y_chunk = y_full.reshape(-1, y_full.shape[2])[start_idx:end_idx]

            log_memory_usage(f"Yielding chunk {start_idx}-{end_idx}")

            yield X_chunk, y_chunk

            # Clean up
            del X_chunk, y_chunk
            cleanup_memory()

    # Clean up full data
    del X_full, y_full
    cleanup_memory()


def get_optimal_batch_size(model: torch.nn.Module, sample_size: int, max_memory_mb: int = 500) -> int:
    """
    Calculate optimal batch size based on available memory.

    Args:
        model: The data-driven model
        sample_size: Size of input features (e.g., 10)
        max_memory_mb: Maximum memory to use for batch processing

    Returns:
        Optimal batch size
    """
    # Estimate memory per sample (rough approximation)
    # Model parameters + activations + gradients
    param_count = sum(p.numel() for p in model.parameters())
    estimated_bytes_per_sample = (param_count * 4) + (sample_size * 4) + 1000  # Rough estimate

    # Reserve some memory for overhead
    available_bytes = max_memory_mb * 1024 * 1024 * 0.7

    batch_size = int(available_bytes // estimated_bytes_per_sample)
    batch_size = max(1, min(batch_size, 10000))  # Reasonable bounds

    logger.debug(f"Estimated batch size: {batch_size} (max memory: {max_memory_mb}MB)")
    return batch_size


def extract_data_driven_residuals(model: torch.nn.Module, X: torch.Tensor, y: torch.Tensor,
                                  scaling_params: Dict, device: torch.device, batch_size: Optional[int] = None) -> Dict[str, np.ndarray]:
    """
    Extract residuals from data-driven model predictions with batch processing.

    Args:
        model: Trained data-driven model
        X: Input features tensor [batch_size, 10]
        y: Target accelerations tensor [batch_size, 4]
        scaling_params: Scaling parameters for normalization/denormalization
        device: Device to run on
        batch_size: Batch size for processing (auto-calculated if None)

    Returns:
        Dictionary containing residuals (data residuals repeated as physics residuals for compatibility)
    """
    model.eval()
    log_memory_usage("Starting residual extraction")

    # Auto-calculate batch size if not provided
    if batch_size is None:
        batch_size = get_optimal_batch_size(model, X.shape[1])

    total_samples = X.shape[0]
    logger.debug(f"Processing {total_samples} samples in batches of {batch_size}")

    # Initialize lists to collect residuals
    all_data_residuals = []

    # Process in batches
    for start_idx in range(0, total_samples, batch_size):
        end_idx = min(start_idx + batch_size, total_samples)

        # Extract batch
        X_batch = X[start_idx:end_idx].to(device)
        y_batch = y[start_idx:end_idx].to(device)

        log_memory_usage(f"Processing batch {start_idx}-{end_idx}")

        # Normalize inputs
        X_norm = (X_batch - scaling_params['Xmin']) / (scaling_params['Xmax'] - scaling_params['Xmin'] + 1e-12)

        with torch.no_grad():
            # Get model predictions
            y_pred_norm = model(X_norm)

            # Denormalize predictions
            y_pred = y_pred_norm * (scaling_params['ymax'] - scaling_params['ymin']) + scaling_params['ymin']

        # Data residuals (prediction errors) - already in physical space
        data_residuals = (y_pred - y_batch).cpu().numpy()

        # Collect residuals
        all_data_residuals.append(data_residuals)

        # Clean up batch
        del X_batch, y_batch, X_norm, y_pred_norm, y_pred
        cleanup_memory()

    # Concatenate all batches
    log_memory_usage("Concatenating results")
    data_residuals_combined = np.concatenate(all_data_residuals, axis=0)

    # For compatibility with PINN pipeline, repeat data residuals as physics residuals
    # This maintains the same 8-feature structure expected by downstream analysis
    residuals_dict = {
        # Data residuals (4 components)
        'data_res1': data_residuals_combined[:, 0],  # x2_ddot residual
        'data_res2': data_residuals_combined[:, 1],  # y2_ddot residual
        'data_res3': data_residuals_combined[:, 2],  # x3_ddot residual
        'data_res4': data_residuals_combined[:, 3],  # y3_ddot residual

        # Physics residuals (repeat data residuals for compatibility)
        'phys_res1': data_residuals_combined[:, 0],  # x2_ddot residual (repeated)
        'phys_res2': data_residuals_combined[:, 1],  # y2_ddot residual (repeated)
        'phys_res3': data_residuals_combined[:, 2],  # x3_ddot residual (repeated)
        'phys_res4': data_residuals_combined[:, 3],  # y3_ddot residual (repeated)
    }

    # Clean up
    del all_data_residuals
    cleanup_memory()

    log_memory_usage("Residual extraction completed")
    return residuals_dict


def extract_data_driven_residuals_streaming(model: torch.nn.Module, data_iterator: Iterator[Tuple[torch.Tensor, torch.Tensor]],
                                          scaling_params: Dict, device: torch.device, total_chunks: Optional[int] = None) -> Iterator[Dict[str, np.ndarray]]:
    """
    Extract data-driven residuals using streaming processing for maximum memory efficiency.

    Args:
        model: Trained data-driven model
        data_iterator: Iterator yielding (X_chunk, y_chunk) tuples
        scaling_params: Scaling parameters for normalization/denormalization
        device: Device to run on
        total_chunks: Total number of chunks for progress bar (optional)

    Yields:
        Dictionary containing residuals for each chunk
    """
    model.eval()
    log_memory_usage("Starting streaming residual extraction")

    # Use progress bar if tqdm available
    if HAS_TQDM and total_chunks:
        with tqdm(total=total_chunks, desc="Processing chunks", unit="chunk") as pbar:
            for chunk_idx, (X_chunk, y_chunk) in enumerate(data_iterator):
                logger.debug(f"Processing chunk {chunk_idx}")

                # Process this chunk
                residuals_chunk = extract_data_driven_residuals(model, X_chunk, y_chunk, scaling_params, device)

                log_memory_usage(f"Chunk {chunk_idx} completed")
                pbar.set_postfix({
                    'chunk': f"{chunk_idx + 1}/{total_chunks}",
                    'samples': f"{X_chunk.shape[0]}"
                })

                yield residuals_chunk

                # Clean up
                del residuals_chunk
                cleanup_memory()
                pbar.update(1)
    else:
        # Fallback without progress bar
        for chunk_idx, (X_chunk, y_chunk) in enumerate(data_iterator):
            logger.debug(f"Processing chunk {chunk_idx}")

            # Process this chunk
            residuals_chunk = extract_data_driven_residuals(model, X_chunk, y_chunk, scaling_params, device)

            log_memory_usage(f"Chunk {chunk_idx} completed")

            yield residuals_chunk

            # Clean up
            del residuals_chunk
            cleanup_memory()


def validate_model_predictions(model, scaling_params, device, sample_data=None):
    """Validate that model predictions are in reasonable ranges."""
    print("[VALIDATION] Validating model predictions...")

    if sample_data is None:
        # Create some sample data for validation
        sample_X = torch.randn(10, 10, device=device, dtype=torch.float64)  # 10 samples, 10 features
        sample_y = torch.randn(10, 4, device=device, dtype=torch.float64)   # 10 samples, 4 outputs
    else:
        sample_X, sample_y = sample_data

    # Normalize sample input
    X_norm = (sample_X - scaling_params['Xmin']) / (scaling_params['Xmax'] - scaling_params['Xmin'] + 1e-12)

    model.eval()
    with torch.no_grad():
        y_pred_norm = model(X_norm)
        y_pred = y_pred_norm * (scaling_params['ymax'] - scaling_params['ymin']) + scaling_params['ymin']

    # Check prediction ranges
    y_pred_mean = torch.mean(y_pred).item()
    y_pred_std = torch.std(y_pred).item()
    y_pred_min = torch.min(y_pred).item()
    y_pred_max = torch.max(y_pred).item()

    print(f"   Model predictions - Mean: {y_pred_mean:.2e}, Std: {y_pred_std:.2e}")
    print(f"   Model predictions - Min: {y_pred_min:.2e}, Max: {y_pred_max:.2e}")

    # Check if predictions are reasonable (not all zeros, not infinite, not extremely large)
    if torch.allclose(y_pred, torch.zeros_like(y_pred), atol=1e-6):
        print("   [WARNING] Model predictions are all zeros!")
    elif torch.any(torch.isinf(y_pred)) or torch.any(torch.isnan(y_pred)):
        print("   [ERROR] Model predictions contain inf or nan values!")
    elif torch.max(torch.abs(y_pred)) > 1e10:
        print("   [WARNING] Extremely large prediction values detected!")
    else:
        print("   [SUCCESS] Model predictions appear reasonable")

    return y_pred


def load_data_driven_model(model_path: str, device: torch.device):
    """Load the trained data-driven model."""
    try:
        # Import here to avoid circular imports
        from models.basicPINNv8 import ConfigurableMLP

        # Create model with fixed architecture (same as PINN best)
        model = ConfigurableMLP(
            input_dim=10,  # 10 features
            hidden_layers=[128, 128],
            output_dim=4,  # 4 accelerations
            activation='elu',
            dropout_rate=0.24900923127192412,
            init_method='xavier_uniform'
        )

        # Load the saved state dict
        state_dict = torch.load(model_path, map_location=device)
        model.load_state_dict(state_dict)

        # Ensure model is in double precision and on correct device
        model = model.double().to(device)

        logger.debug("Successfully loaded data-driven model")
        return model

    except Exception as e:
        logger.error(f"Error loading data-driven model: {e}")
        raise


def load_scaling_params_from_data_driven(model_path: str) -> dict:
    """Load scaling parameters from data-driven model training."""
    # Look for scaling parameters in the data directory
    scaling_path = "Data/v3/scaling_params.npz"

    if not os.path.exists(scaling_path):
        raise FileNotFoundError(f"Scaling parameters file not found: {scaling_path}")

    scaling_data = np.load(scaling_path)
    scaling_params = {
        'Xmin': torch.from_numpy(scaling_data['Xmin']).double(),
        'Xmax': torch.from_numpy(scaling_data['Xmax']).double(),
        'ymin': torch.from_numpy(scaling_data['ymin']).double(),
        'ymax': torch.from_numpy(scaling_data['ymax']).double()
    }

    return scaling_params


def create_data_derived_scaling_params(data_path: str, device: torch.device = None) -> dict:
    """
    Create scaling parameters derived from the actual data range.
    This is a better fallback than identity transform as it uses the data's natural range.

    Args:
        data_path: Path to the X data file (will automatically find corresponding Y file)
        device: Device to place tensors on

    Returns:
        Dictionary with Xmin, Xmax, ymin, ymax tensors
    """
    if device is None:
        device = torch.device('cpu')

    # Load the data to compute actual min/max values
    X, y = load_pinn_data(data_path)

    # Compute scaling parameters from data
    # Flatten across rotation speeds and time to get global min/max per feature
    X_flat = X.reshape(-1, X.shape[-1])  # [total_samples, 10]
    y_flat = y.reshape(-1, y.shape[-1])  # [total_samples, 4]

    X_min = X_flat.min(dim=0)[0]  # Min across all samples for each feature
    X_max = X_flat.max(dim=0)[0]  # Max across all samples for each feature
    y_min = y_flat.min(dim=0)[0]  # Min across all samples for each output
    y_max = y_flat.max(dim=0)[0]  # Max across all samples for each output

    scaling_params = {
        'Xmin': X_min.double().to(device),
        'Xmax': X_max.double().to(device),
        'ymin': y_min.double().to(device),
        'ymax': y_max.double().to(device)
    }

    return scaling_params


def preprocess_data_driven_data(data_path: str, chunk_size_mb: int = 50) -> Dict[str, np.ndarray]:
    """
    Preprocess data using a trained data-driven model to extract residuals (maximum memory efficiency).

    Uses streaming processing to handle large datasets with minimal RAM usage.

    Args:
        data_path: Path to .pth data file (from LoadDatav3.py)
        chunk_size_mb: Target chunk size in MB (smaller = less RAM, slower processing)

    Returns:
        Dictionary containing 8 residual features:
        - data_res1, data_res2, data_res3, data_res4: Data residuals
        - phys_res1, phys_res2, phys_res3, phys_res4: Physics residuals (repeated data residuals)
    """
    log_memory_usage("Starting maximum memory efficiency preprocessing")

    # Force CPU usage for lower memory overhead
    device = torch.device('cpu')
    logger.debug("Using CPU device for maximum memory efficiency")

    # Load data-driven model and scaling parameters
    logger.info("Loading data-driven model")

    # Try to find the most recent data-driven model
    # Look in the parent directory's results folder (from josafat root)
    results_dir = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "results")
    data_driven_dirs = [d for d in os.listdir(results_dir) if d.startswith("data_driven_")]
    if not data_driven_dirs:
        raise FileNotFoundError(f"No data-driven model directories found in {results_dir}")

    # Get the most recent directory
    latest_dir = max(data_driven_dirs, key=lambda x: os.path.getctime(os.path.join(results_dir, x)))
    model_path = os.path.join(results_dir, latest_dir, "best_model.pth")

    if not os.path.exists(model_path):
        raise FileNotFoundError(f"Data-driven model file not found: {model_path}")

    logger.info(f"Using data-driven model from: {model_path}")
    logger.info(f"Available data-driven directories: {data_driven_dirs}")
    logger.info(f"Latest directory: {latest_dir}")

    model = load_data_driven_model(model_path, device)

    # Load scaling parameters
    try:
        scaling_params = load_scaling_params_from_data_driven(model_path)
    except FileNotFoundError:
        logger.warning("Scaling parameters not found for data-driven model, using data-derived normalization")
        # Create data-derived scaling parameters (much better than identity transform)
        scaling_params = create_data_derived_scaling_params(data_path, device)

    logger.info("Successfully loaded data-driven model")

    log_memory_usage("Model loaded")

    # Validate model predictions with a small sample
    validate_model_predictions(model, scaling_params, device)

    # Calculate total chunks for progress reporting
    # First load data to get dimensions, then clean up immediately
    X_temp, y_temp = load_pinn_data(data_path)
    total_samples = X_temp.shape[0] * X_temp.shape[1]
    bytes_per_sample = X_temp.element_size() * (X_temp.shape[2] + y_temp.shape[2])
    target_samples_per_chunk = (chunk_size_mb * 1024 * 1024) // bytes_per_sample
    total_chunks = (total_samples + target_samples_per_chunk - 1) // target_samples_per_chunk
    del X_temp, y_temp
    cleanup_memory()

    # Use streaming processing for maximum memory efficiency
    logger.debug(f"Using streaming processing with {chunk_size_mb}MB chunks ({total_chunks} total chunks)")

    # Collect all residuals
    all_residuals = {}
    residual_keys = ['data_res1', 'data_res2', 'data_res3', 'data_res4',
                    'phys_res1', 'phys_res2', 'phys_res3', 'phys_res4']

    # Initialize lists for each residual type
    for key in residual_keys:
        all_residuals[key] = []

    # Process in chunks with progress bar
    logger.info(f"Starting preprocessing with {total_chunks} chunks")
    data_iterator = load_pinn_data_chunked(data_path, chunk_size_mb)
    residuals_iterator = extract_data_driven_residuals_streaming(model, data_iterator, scaling_params, device, total_chunks)

    chunk_count = 0
    if HAS_TQDM:
        with tqdm(total=total_chunks, desc="Preprocessing data", unit="chunk") as overall_pbar:
            for chunk_residuals in residuals_iterator:
                chunk_count += 1
                logger.debug(f"Processed chunk {chunk_count}/{total_chunks}")
                # Accumulate residuals from this chunk
                for key in residual_keys:
                    all_residuals[key].append(chunk_residuals[key])
                overall_pbar.update(1)
    else:
        # Fallback without progress bar
        for chunk_residuals in residuals_iterator:
            chunk_count += 1
            logger.debug(f"Processed chunk {chunk_count}/{total_chunks}")
            # Accumulate residuals from this chunk
            for key in residual_keys:
                all_residuals[key].append(chunk_residuals[key])

    logger.info(f"Processed {chunk_count} chunks total")

    # Concatenate all chunks
    log_memory_usage("Concatenating streaming results")
    final_residuals = {}
    for key in residual_keys:
        final_residuals[key] = np.concatenate(all_residuals[key], axis=0)

    # Clean up
    del all_residuals
    cleanup_memory()

    log_memory_usage("Maximum memory efficiency preprocessing completed")
    return final_residuals


def get_residual_features(residuals_dict: Dict[str, np.ndarray]) -> np.ndarray:
    """
    Convert residuals dictionary to feature matrix for machine learning.

    Args:
        residuals_dict: Dictionary from preprocess_data_driven_data

    Returns:
        Feature matrix of shape [num_samples, 8]
    """
    features = np.column_stack([
        residuals_dict['data_res1'], residuals_dict['data_res2'],
        residuals_dict['data_res3'], residuals_dict['data_res4'],
        residuals_dict['phys_res1'], residuals_dict['phys_res2'],
        residuals_dict['phys_res3'], residuals_dict['phys_res4']
    ])
    return features


def get_rotation_speed_separated_features(data_path: str, chunk_size_mb: int = 50) -> np.ndarray:
    """
    Get features separated by rotation speed: [n_rotation_speeds, n_timestamps_per_speed, 8]

    Args:
        data_path: Path to .pth file from LoadDatav3.py
        chunk_size_mb: Target chunk size in MB for streaming processing

    Returns:
        Array of shape [n_rotation_speeds, n_timestamps_per_speed, 8]
    """
    log_memory_usage("Starting rotation speed separated features")

    # Load raw data to get dimensions
    X, y = load_pinn_data(data_path)
    n_rotation_speeds, n_timestamps_per_speed = X.shape[0], X.shape[1]
    log_memory_usage(f"Data shape: {X.shape}")

    # Clean up the initial data load immediately
    del X, y
    cleanup_memory()

    # Get residuals using preprocessing
    residuals = preprocess_data_driven_data(data_path, chunk_size_mb)

    # Convert to feature matrix
    features_flat = get_residual_features(residuals)  # [total_samples, 8]

    # Reshape back to separated format
    features_separated = features_flat.reshape(
        n_rotation_speeds,
        n_timestamps_per_speed,
        8
    )

    # Clean up
    del residuals, features_flat
    cleanup_memory()

    log_memory_usage("Rotation speed separated features completed")
    return features_separated


# ============================================================================
# MAXIMUM MEMORY EFFICIENCY DATA-DRIVEN PREPROCESSING
# ============================================================================
#
# This module processes large datasets with minimal RAM usage using:
# - Streaming processing (loads data in chunks)
# - Automatic memory cleanup
# - CPU-only processing for lower memory overhead
# - Memory monitoring (if psutil installed)
# - Progress bars (if tqdm installed)
#
# BASIC USAGE:
#   from training_scripts.data_driven_preprocessing import preprocess_data_driven_data
#   residuals = preprocess_data_driven_data('Data/v3/X_normal_v3.pth')
#
# CONTROL MEMORY USAGE:
#   # Smaller chunks = less RAM, slower processing
#   residuals = preprocess_data_driven_data('Data/v3/X_normal_v3.pth', chunk_size_mb=25)
#
#   # Larger chunks = more RAM, faster processing
#   residuals = preprocess_data_driven_data('Data/v3/X_normal_v3.pth', chunk_size_mb=100)
#
# ROTATION SPEED FEATURES:
#   from training_scripts.data_driven_preprocessing import get_rotation_speed_separated_features
#   features = get_rotation_speed_separated_features('Data/v3/X_normal_v3.pth')
#
# DATA-DRIVEN MODEL TRAINING:
#   python training_scripts/data_driven_training.py --data-path Data --max-samples 1000
#
# ============================================================================

def main():
    """Main function to generate 8-channel residuals from data-driven model."""

    import argparse

    parser = argparse.ArgumentParser(description='Generate 8-channel residuals from data-driven model')
    parser.add_argument('--data-path', type=str, required=True,
                       help='Path to data file (X_*.pth)')
    parser.add_argument('--output', type=str, required=True,
                       help='Output path for residuals (.pth file)')
    parser.add_argument('--chunk-size-mb', type=int, default=50,
                       help='Target chunk size in MB for streaming processing')
    parser.add_argument('--use-fraction', type=float, default=1.0,
                       help='Fraction of data to use (default: 1.0 for all data, 0.2 for 20%%)')
    parser.add_argument('--test-mode', action='store_true',
                       help='Fast test mode - process only first 10 chunks')

    args = parser.parse_args()

    logger.info("Starting 8-channel residual generation for data-driven baseline")
    logger.info(f"Data: {args.data_path}")
    logger.info(f"Output: {args.output}")
    logger.info(f"Chunk size: {args.chunk_size_mb} MB")
    logger.info(f"Data fraction: {args.use_fraction * 100:.0f}%")
    if args.test_mode:
        logger.info("TEST MODE: Processing only first 10 chunks")

    # Use streaming processing for maximum memory efficiency
    logger.info("Starting preprocessing...")

    # Temporarily modify the preprocess function to support test mode
    # We'll monkey-patch it for this script
    original_preprocess = preprocess_data_driven_data

    def preprocess_with_test_mode(data_path: str, chunk_size_mb: int = 50) -> Dict[str, np.ndarray]:
        """Wrapper to add test mode support."""
        log_memory_usage("Starting maximum memory efficiency preprocessing")

        # Force CPU usage for lower memory overhead
        device = torch.device('cpu')
        logger.debug("Using CPU device for maximum memory efficiency")

        # Load data-driven model and scaling parameters
        logger.info("Loading data-driven model")

        # Try to find the most recent data-driven model
        results_dir = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "results")
        data_driven_dirs = [d for d in os.listdir(results_dir) if d.startswith("data_driven_")]
        if not data_driven_dirs:
            raise FileNotFoundError(f"No data-driven model directories found in {results_dir}")

        # Get the most recent directory
        latest_dir = max(data_driven_dirs, key=lambda x: os.path.getctime(os.path.join(results_dir, x)))
        model_path = os.path.join(results_dir, latest_dir, "best_model.pth")

        if not os.path.exists(model_path):
            raise FileNotFoundError(f"Data-driven model file not found: {model_path}")

        logger.info(f"Using data-driven model from: {model_path}")
        logger.info(f"Available data-driven directories: {data_driven_dirs}")
        logger.info(f"Latest directory: {latest_dir}")

        model = load_data_driven_model(model_path, device)

        # Load scaling parameters
        try:
            scaling_params = load_scaling_params_from_data_driven(model_path)
        except FileNotFoundError:
            logger.warning("Scaling parameters not found for data-driven model, using data-derived normalization")
            scaling_params = create_data_derived_scaling_params(data_path, device)

        logger.info("Successfully loaded data-driven model")

        log_memory_usage("Model loaded")

        # Validate model predictions with a small sample
        validate_model_predictions(model, scaling_params, device)

        # Calculate total chunks for progress reporting
        X_temp, y_temp = load_pinn_data(data_path)
        original_total_samples = X_temp.shape[0] * X_temp.shape[1]

        # Apply fraction to get actual samples we'll process
        if args.use_fraction < 1.0:
            stride = max(1, int(1.0 / args.use_fraction))
            actual_total_samples = (original_total_samples + stride - 1) // stride  # Ceiling division
        else:
            actual_total_samples = original_total_samples

        bytes_per_sample = X_temp.element_size() * (X_temp.shape[2] + y_temp.shape[2])
        target_samples_per_chunk = (chunk_size_mb * 1024 * 1024) // bytes_per_sample
        total_chunks = (actual_total_samples + target_samples_per_chunk - 1) // target_samples_per_chunk
        del X_temp, y_temp
        cleanup_memory()

        if args.test_mode:
            total_chunks = min(10, total_chunks)  # Only process first 10 chunks in test mode

        # Use streaming processing for maximum memory efficiency
        logger.debug(f"Using streaming processing with {chunk_size_mb}MB chunks ({total_chunks} total chunks)")

        # Collect all residuals
        all_residuals = {}
        residual_keys = ['data_res1', 'data_res2', 'data_res3', 'data_res4',
                        'phys_res1', 'phys_res2', 'phys_res3', 'phys_res4']

        # Initialize lists for each residual type
        for key in residual_keys:
            all_residuals[key] = []

        # Process in chunks with progress bar
        logger.info(f"Starting preprocessing with {total_chunks} chunks")

        # Apply fraction sampling by modifying chunk loading
        if args.use_fraction < 1.0:
            # Load full data, apply fraction sampling per rotation speed, then create chunks
            logger.info(f"Applying fraction sampling: {args.use_fraction * 100:.0f}% of data")
            X_full, y_full = load_pinn_data(data_path)

            # Calculate stride for sampling within each rotation speed
            stride = max(1, int(1.0 / args.use_fraction))
            logger.info(f"Using sampling stride: {stride} (samples every {stride}th point per rotation speed)")

            # Sample within each rotation speed segment (preserve speed structure)
            n_rot_speeds, n_timestamps_per_speed, n_features_x = X_full.shape
            n_features_y = y_full.shape[2]

            X_sampled = []
            y_sampled = []

            for rot_speed_idx in range(n_rot_speeds):
                # Sample timestamps within this rotation speed
                speed_timestamps = np.arange(0, n_timestamps_per_speed, stride)
                X_speed = X_full[rot_speed_idx, speed_timestamps, :]  # [sampled_timestamps, features]
                y_speed = y_full[rot_speed_idx, speed_timestamps, :]  # [sampled_timestamps, features]

                X_sampled.append(X_speed)
                y_sampled.append(y_speed)

            # Stack back together
            X_full = torch.stack(X_sampled, dim=0)  # [n_rot_speeds, sampled_timestamps, features]
            y_full = torch.stack(y_sampled, dim=0)  # [n_rot_speeds, sampled_timestamps, features]

            original_samples = n_rot_speeds * n_timestamps_per_speed
            new_samples = X_full.shape[0] * X_full.shape[1]
            logger.info(f"Data reduced from {original_total_samples} to {new_samples} samples "
                       f"({original_total_samples//n_rot_speeds} -> {new_samples//n_rot_speeds} per rotation speed)")

            # Flatten the sampled data and use chunked loading
            X_full = X_full.reshape(-1, n_features_x)  # [total_samples, features]
            y_full = y_full.reshape(-1, n_features_y)  # [total_samples, features]

            # Create data iterator using chunked loading
            data_iterator = load_pinn_data_chunked_from_tensor(X_full, y_full, chunk_size_mb)
            residuals_iterator = extract_data_driven_residuals_streaming(model, data_iterator, scaling_params, device, total_chunks)
        else:
            # Use standard chunked loading for full data
            data_iterator = load_pinn_data_chunked(data_path, chunk_size_mb)
            residuals_iterator = extract_data_driven_residuals_streaming(model, data_iterator, scaling_params, device, total_chunks)

        chunk_count = 0
        if HAS_TQDM:
            with tqdm(total=total_chunks, desc="Preprocessing data", unit="chunk") as overall_pbar:
                for chunk_residuals in residuals_iterator:
                    chunk_count += 1
                    logger.debug(f"Processed chunk {chunk_count}/{total_chunks}")
                    # Accumulate residuals from this chunk
                    for key in residual_keys:
                        all_residuals[key].append(chunk_residuals[key])
                    overall_pbar.update(1)

                    if args.test_mode and chunk_count >= 10:
                        logger.info("TEST MODE: Stopping after 10 chunks")
                        break
        else:
            # Fallback without progress bar
            for chunk_residuals in residuals_iterator:
                chunk_count += 1
                logger.debug(f"Processed chunk {chunk_count}/{total_chunks}")
                # Accumulate residuals from this chunk
                for key in residual_keys:
                    all_residuals[key].append(chunk_residuals[key])

                if args.test_mode and chunk_count >= 10:
                    logger.info("TEST MODE: Stopping after 10 chunks")
                    break

        logger.info(f"Processed {chunk_count} chunks total")

        # Concatenate all chunks
        log_memory_usage("Concatenating streaming results")
        final_residuals = {}
        for key in residual_keys:
            final_residuals[key] = np.concatenate(all_residuals[key], axis=0)

        # Clean up
        del all_residuals
        cleanup_memory()

        log_memory_usage("Maximum memory efficiency preprocessing completed")
        return final_residuals

    # Run preprocessing
    residuals = preprocess_with_test_mode(args.data_path, args.chunk_size_mb)

    # Save residuals with higher pickle protocol to handle large files
    logger.info(f"Saving 8-channel residuals to {args.output}")

    # Convert numpy arrays to torch tensors for efficient saving
    torch_dict = {}
    for key, residuals_array in residuals.items():
        torch_dict[key] = torch.from_numpy(residuals_array).float()

    # Use pickle protocol 4 to handle large files (>4GB)
    import pickle
    with open(args.output, 'wb') as f:
        pickle.dump(torch_dict, f, protocol=4)

    logger.info(f"Successfully saved {len(torch_dict)} residual channels")

    # Log final statistics
    logger.info("Final residual statistics:")
    for key, residuals_array in residuals.items():
        logger.info(f"  {key}: {len(residuals_array)} samples, "
                   f"mean {np.mean(residuals_array):.6f}, std {np.std(residuals_array):.6f}")

    if args.test_mode:
        logger.info("✅ TEST MODE: 8-channel residual generation completed (partial)!")
    else:
        logger.info("✅ 8-channel residual generation completed!")


def load_pinn_data_chunked_from_tensor(X_tensor: torch.Tensor, y_tensor: torch.Tensor, chunk_size_mb: int = 100) -> Iterator[Tuple[torch.Tensor, torch.Tensor]]:
    """
    Load X and y tensors in chunks from already loaded tensors.

    Args:
        X_tensor: Input features tensor [total_samples, features]
        y_tensor: Target values tensor [total_samples, features]
        chunk_size_mb: Target chunk size in MB

    Yields:
        Tuples of (X_chunk, y_chunk) tensors
    """
    total_samples = X_tensor.shape[0]
    bytes_per_sample = X_tensor.element_size() * (X_tensor.shape[1] + y_tensor.shape[1])
    target_samples_per_chunk = (chunk_size_mb * 1024 * 1024) // bytes_per_sample

    # Calculate number of chunks for progress bar
    total_chunks = (total_samples + target_samples_per_chunk - 1) // target_samples_per_chunk

    logger.debug(f"Data: {total_samples} samples, ~{bytes_per_sample} bytes per sample")
    logger.debug(f"Target chunk size: {target_samples_per_chunk} samples ({total_chunks} chunks)")

    # Process in chunks
    for start_idx in range(0, total_samples, target_samples_per_chunk):
        end_idx = min(start_idx + target_samples_per_chunk, total_samples)

        # Extract chunk
        X_chunk = X_tensor[start_idx:end_idx]
        y_chunk = y_tensor[start_idx:end_idx]

        log_memory_usage(f"Yielding chunk {start_idx}-{end_idx}")
        yield X_chunk, y_chunk

        # Clean up
        del X_chunk, y_chunk
        cleanup_memory()


if __name__ == '__main__':
    main()